 <!DOCTYPE html>
 <html lang="en">
 <head>
 <meta charset="UTF-8" />
 <title>A/L Exam Results Lookup</title>
 <link rel="stylesheet" href="style.css" />
 </head>
 <body>
 <div class="container">
 <h1>A/L Results Lookup</h1>
 <form id="lookupForm">
 <label for="indexInput">Enter your Index Number:</label>
 <input type="text" id="indexInput" maxlength="7" required />
 <button type="submit">Check Result</button>
 <div class="error" id="error"></div>
 </form>
 <div id="result"></div>
 </div>
 <script src="script.js"></script>
 </body>
 </html>
